name: Change-o
favicon: null
layout_spectrum: 0.3326571271754801
typography_spectrum: 0.0019794327672570944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.581489234464243
  lightness: 0.11981140589341521
  saturation: 0.09543573064729571
  rhythmicContrast: 0.6082214552443475
purpose: []
